/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/payments` | `/payments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/schedule` | `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `/admin/configuracion`; params?: Router.UnknownInputParams; } | { pathname: `/admin/espacios`; params?: Router.UnknownInputParams; } | { pathname: `/admin/familias`; params?: Router.UnknownInputParams; } | { pathname: `/admin/finanzas`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/admin/noticias`; params?: Router.UnknownInputParams; } | { pathname: `/admin/operacion`; params?: Router.UnknownInputParams; } | { pathname: `/admin/socios`; params?: Router.UnknownInputParams; } | { pathname: `/admin/usuarios`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/payments` | `/payments`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/schedule` | `/schedule`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/configuracion`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/espacios`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/familias`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/finanzas`; params?: Router.UnknownOutputParams; } | { pathname: `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/noticias`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/operacion`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/socios`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/usuarios`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/explore${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/payments${`?${string}` | `#${string}` | ''}` | `/payments${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/schedule${`?${string}` | `#${string}` | ''}` | `/schedule${`?${string}` | `#${string}` | ''}` | `/admin/configuracion${`?${string}` | `#${string}` | ''}` | `/admin/espacios${`?${string}` | `#${string}` | ''}` | `/admin/familias${`?${string}` | `#${string}` | ''}` | `/admin/finanzas${`?${string}` | `#${string}` | ''}` | `/admin${`?${string}` | `#${string}` | ''}` | `/admin/noticias${`?${string}` | `#${string}` | ''}` | `/admin/operacion${`?${string}` | `#${string}` | ''}` | `/admin/socios${`?${string}` | `#${string}` | ''}` | `/admin/usuarios${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/payments` | `/payments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/schedule` | `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `/admin/configuracion`; params?: Router.UnknownInputParams; } | { pathname: `/admin/espacios`; params?: Router.UnknownInputParams; } | { pathname: `/admin/familias`; params?: Router.UnknownInputParams; } | { pathname: `/admin/finanzas`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/admin/noticias`; params?: Router.UnknownInputParams; } | { pathname: `/admin/operacion`; params?: Router.UnknownInputParams; } | { pathname: `/admin/socios`; params?: Router.UnknownInputParams; } | { pathname: `/admin/usuarios`; params?: Router.UnknownInputParams; };
    }
  }
}
