import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Brand } from '@/constants/theme';
import { useAuth } from '@/context/AuthContext';
import { apiFetch } from '@/lib/api';
type Config = { slug: string; nombre: string; color_primario: string; cuota_monto: number; activo: boolean; onboarding_completo: boolean; titular_nombre: string | null; titular_apellido: string | null; ciudad: string | null; provincia: string | null; deportes: string[]; bloquear_reservas?: boolean; max_reservas_activas?: number; cancelar_reserva_horas?: number };
export default function ConfiguracionScreen() { const { session } = useAuth(); const [club, setClub] = useState<Config | null>(null); const [nombre, setNombre] = useState(''); const [cuota, setCuota] = useState(''); const [color, setColor] = useState(''); const [deportes, setDeportes] = useState(''); const [maxReservas, setMaxReservas] = useState(''); const [cancelarHoras, setCancelarHoras] = useState(''); const [bloquear, setBloquear] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
 const load = useCallback(async () => { if (!session) return; setLoading(true); try { const data = await apiFetch<Config>('/clubs/me', {}, session.access_token); setClub(data); setNombre(data.nombre); setCuota(String(data.cuota_monto ?? '')); setColor(data.color_primario); setDeportes(data.deportes?.join(', ') ?? ''); setMaxReservas(String(data.max_reservas_activas ?? '')); setCancelarHoras(String(data.cancelar_reserva_horas ?? '')); setBloquear(Boolean(data.bloquear_reservas)); setError(''); } catch (err) { setError(err instanceof Error ? err.message : 'No se pudo cargar la configuración'); } finally { setLoading(false); } }, [session]);
 useEffect(() => { void load(); }, [load]);
 async function save() { if (!session || !nombre.trim() || !/^#[0-9a-fA-F]{6}$/.test(color)) { setError('Completá nombre y un color hexadecimal válido'); return; } setSaving(true); try { const data = await apiFetch<Config>('/clubs/me', { method: 'PATCH', body: JSON.stringify({ nombre: nombre.trim(), cuota_monto: Number(cuota), color_primario: color, deportes: deportes.split(',').map((d) => d.trim()).filter(Boolean), bloquear_reservas: bloquear, ...(maxReservas ? { max_reservas_activas: Number(maxReservas) } : {}), ...(cancelarHoras ? { cancelar_reserva_horas: Number(cancelarHoras) } : {}) }) }, session.access_token); setClub(data); setError(''); } catch (err) { setError(err instanceof Error ? err.message : 'No se pudo guardar'); } finally { setSaving(false); } }
 return <ScrollView style={styles.screen} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} />}><View style={styles.intro}><View style={styles.icon}><Ionicons name="settings-outline" size={25} color={Brand.primary} /></View><View><Text style={styles.title}>Configuración</Text><Text style={styles.subtitle}>Preferencias y datos del club</Text></View></View>{!!error && <Text style={styles.error}>{error}</Text>}{loading && !club ? <ActivityIndicator color={Brand.primary} style={styles.loader} /> : club ? <><View style={styles.card}><Text style={styles.cardTitle}>Datos editables</Text><Text style={styles.label}>Nombre del club</Text><TextInput value={nombre} onChangeText={setNombre} style={styles.input} /><Text style={styles.label}>Cuota socio pleno</Text><TextInput value={cuota} onChangeText={setCuota} keyboardType="numeric" style={styles.input} /><Text style={styles.label}>Color principal (#RRGGBB)</Text><TextInput value={color} onChangeText={setColor} autoCapitalize="none" style={styles.input} /><Text style={styles.label}>Deportes (separados por coma)</Text><TextInput value={deportes} onChangeText={setDeportes} style={styles.input} /><Text style={styles.label}>Máximo de reservas activas</Text><TextInput value={maxReservas} onChangeText={setMaxReservas} keyboardType="numeric" style={styles.input} /><Text style={styles.label}>Horas mínimas para cancelar</Text><TextInput value={cancelarHoras} onChangeText={setCancelarHoras} keyboardType="numeric" style={styles.input} /><View style={styles.switchRow}><Text style={styles.detail}>Bloquear reservas</Text><Switch value={bloquear} onValueChange={setBloquear} trackColor={{ true: Brand.primary }} /></View><TouchableOpacity style={styles.button} onPress={save} disabled={saving}><Text style={styles.buttonText}>{saving ? 'Guardando…' : 'Guardar cambios'}</Text></TouchableOpacity></View><View style={styles.card}><Text style={styles.cardTitle}>{club.nombre}</Text><Text style={styles.detail}>Slug: {club.slug}</Text><Text style={styles.detail}>Titular: {club.titular_nombre ?? '—'} {club.titular_apellido ?? ''}</Text><Text style={styles.detail}>Ubicación: {[club.ciudad, club.provincia].filter(Boolean).join(', ') || '—'}</Text><Text style={styles.detail}>Estado: {club.activo ? 'Activo' : 'Inactivo'}</Text><Text style={styles.detail}>Onboarding: {club.onboarding_completo ? 'Completo' : 'Pendiente'}</Text></View></> : null}</ScrollView>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: Brand.surface }, content: { padding: 16, paddingBottom: 110 }, intro: { flexDirection: 'row', alignItems: 'center', marginBottom: 22 }, icon: { width: 52, height: 52, borderRadius: 15, backgroundColor: '#e5eeff', alignItems: 'center', justifyContent: 'center', marginRight: 13 }, title: { color: Brand.text, fontSize: 24, fontWeight: '700' }, subtitle: { color: Brand.muted, fontSize: 13, marginTop: 3 }, card: { backgroundColor: '#fff', borderColor: Brand.border, borderWidth: 1, borderRadius: 12, padding: 16, marginBottom: 12 }, cardTitle: { color: Brand.text, fontSize: 17, fontWeight: '700', marginBottom: 8 }, label: { color: Brand.text, fontSize: 12, fontWeight: '600', marginTop: 8, marginBottom: 5 }, input: { height: 44, borderColor: '#c4c5d5', borderWidth: 1, borderRadius: 8, paddingHorizontal: 12, color: Brand.text }, detail: { color: Brand.muted, fontSize: 13, marginTop: 6 }, switchRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 10 }, button: { height: 46, borderRadius: 8, backgroundColor: Brand.primary, alignItems: 'center', justifyContent: 'center', marginTop: 16 }, buttonText: { color: '#fff', fontWeight: '700' }, color: { borderRadius: 8, padding: 10, marginTop: 12 }, colorText: { color: '#fff', fontWeight: '700', fontSize: 12 }, loader: { marginTop: 30 }, error: { color: '#ba1a1a', marginBottom: 12 } });
