import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Brand } from '@/constants/theme';
import { useAuth } from '@/context/AuthContext';
import { apiFetch } from '@/lib/api';

type Espacio = { id: number; nombre: string; tipo: string; activo: boolean };
type Reserva = { id: number; inicio: string; fin: string; estado: string; socio: { nombre: string; apellido: string }; espacio: { nombre: string } };
export default function EspaciosScreen() {
  const { session } = useAuth(); const [espacios, setEspacios] = useState<Espacio[]>([]); const [reservas, setReservas] = useState<Reserva[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { if (!session) return; setLoading(true); try { const [e, r] = await Promise.all([apiFetch<Espacio[]>('/espacios', {}, session.access_token), apiFetch<Reserva[]>('/reservas', {}, session.access_token)]); setEspacios(e); setReservas(r); setError(''); } catch (err) { setError(err instanceof Error ? err.message : 'No se pudieron cargar espacios y reservas'); } finally { setLoading(false); } }, [session]);
  useEffect(() => { void load(); }, [load]);
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} />}>
    <View style={styles.intro}><View style={styles.icon}><Ionicons name="business-outline" size={25} color={Brand.primary} /></View><View><Text style={styles.title}>Espacios y reservas</Text><Text style={styles.subtitle}>Operación de instalaciones del club</Text></View></View>
    {!!error && <Text style={styles.error}>{error}</Text>}
    {loading && !espacios.length && !reservas.length ? <ActivityIndicator color={Brand.primary} style={styles.loader} /> : <><Text style={styles.sectionTitle}>Espacios ({espacios.length})</Text>{espacios.length ? <View style={styles.list}>{espacios.map((e) => <View key={e.id} style={styles.row}><Ionicons name="business-outline" size={20} color={Brand.primary} /><View style={styles.rowText}><Text style={styles.name}>{e.nombre}</Text><Text style={styles.detail}>{e.tipo}</Text></View><Text style={styles.status}>{e.activo ? 'Activo' : 'Inactivo'}</Text></View>)}</View> : <Text style={styles.emptyText}>No hay espacios cargados.</Text>}<Text style={styles.sectionTitle}>Reservas ({reservas.length})</Text>{reservas.length ? <View style={styles.list}>{reservas.slice(0, 30).map((r) => <View key={r.id} style={styles.row}><Ionicons name="calendar-outline" size={20} color={Brand.primary} /><View style={styles.rowText}><Text style={styles.name}>{r.espacio.nombre}</Text><Text style={styles.detail}>{r.socio.apellido}, {r.socio.nombre} · {new Date(r.inicio).toLocaleString('es-AR')}</Text></View><Text style={styles.status}>{r.estado}</Text></View>)}</View> : <Text style={styles.emptyText}>No hay reservas registradas.</Text>}</>}
  </ScrollView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: Brand.surface }, content: { padding: 16, paddingBottom: 110 }, intro: { flexDirection: 'row', alignItems: 'center', marginBottom: 22 }, icon: { width: 52, height: 52, borderRadius: 15, backgroundColor: '#e5eeff', alignItems: 'center', justifyContent: 'center', marginRight: 13 }, title: { color: Brand.text, fontSize: 24, fontWeight: '700' }, subtitle: { color: Brand.muted, fontSize: 13, marginTop: 3 }, sectionTitle: { color: Brand.text, fontSize: 17, fontWeight: '700', marginTop: 8, marginBottom: 10 }, list: { backgroundColor: '#fff', borderColor: Brand.border, borderWidth: 1, borderRadius: 12, overflow: 'hidden' }, row: { flexDirection: 'row', alignItems: 'center', padding: 13, borderBottomColor: Brand.border, borderBottomWidth: 1 }, rowText: { flex: 1, marginLeft: 11 }, name: { color: Brand.text, fontWeight: '700', fontSize: 14 }, detail: { color: Brand.muted, fontSize: 11, marginTop: 4 }, status: { color: Brand.primary, fontSize: 11, fontWeight: '700' }, loader: { marginTop: 30 }, error: { color: '#ba1a1a', marginBottom: 12 }, emptyText: { color: Brand.muted, fontSize: 13, marginBottom: 12 } });
